#!/bin/bash
# Tries to help you set up an emscripten JS cross-compile if you pass the path
#  to your emscripten dir as the first arg.  Because emscripten provides the
#  helpful "emconfigure" script, we don't have to do much.
EMDIR=$1
shift

export EMCC_DEBUG=1

#${EMDIR}/emmake bash -c "env | sort"
#${EMDIR}/emconfigure bash -c "env | sort"
${EMDIR}/emconfigure ./waf "$@" configure
${EMDIR}/emmake ./waf "$@" build

#${EMDIR}/emcc build/libnacl.so -o build/libnacl.js
